#pragma once

namespace Video{
	std::string ids_config_template_ = 
"\n"
"[Versions]\n"
"libueye_api.so=4.82.16\n"
"ueyed-usb=4.82.16\n"
"ueye_boot.sys=4.82.16\n"
"\n"
"\n"
"[Sensor]\n"
"Sensor=UI388xCP-C\n"
"Sensor bit depth=0\n"
"Sensor source gain=10\n"
"FPN correction mode=0\n"
"Black reference mode=0\n"
"Sensor digital gain=0\n"
"\n"
"\n"
"[Image size]\n"
"Start X=0\n"
"Start Y=0\n"
"Start X absolute=0\n"
"Start Y absolute=0\n"
"Width=3088\n"
"Height=2076\n"
"Binning=0\n"
"Subsampling=0\n"
"\n"
"\n"
"[Scaler]\n"
"Mode=0\n"
"Factor=0.000000\n"
"\n"
"\n"
"[Multi AOI]\n"
"Enabled=0\n"
"Mode=0\n"
"x1=0\n"
"x2=0\n"
"x3=0\n"
"x4=0\n"
"y1=0\n"
"y2=0\n"
"y3=0\n"
"y4=0\n"
"\n"
"\n"
"[Shutter]\n"
"Mode=0\n"
"Linescan number=0\n"
"\n"
"\n"
"[Log Mode]\n"
"Mode=3\n"
"Manual value=0\n"
"Manual gain=0\n"
"\n"
"\n"
"[Timing]\n"
"Pixelclock=197\n"
"Extended pixelclock range=0\n"
"Framerate=15.00\n"
"Exposure=2.\n"
"Long exposure=0\n"
"Dual exposure ratio=0\n"
"\n"
"\n"
"[Selected Converter]\n"
"IS_SET_CM_RGB32=2\n"
"IS_SET_CM_RGB24=8\n"
"IS_SET_CM_RGB16=2\n"
"IS_SET_CM_RGB15=2\n"
"IS_SET_CM_Y8=2\n"
"IS_SET_CM_RGB8=2\n"
"IS_SET_CM_BAYER=8\n"
"IS_SET_CM_UYVY=2\n"
"IS_SET_CM_UYVY_MONO=2\n"
"IS_SET_CM_UYVY_BAYER=2\n"
"IS_CM_CBYCRY_PACKED=0\n"
"IS_SET_CM_RGBY=8\n"
"IS_SET_CM_RGB30=2\n"
"IS_SET_CM_Y12=2\n"
"IS_SET_CM_BAYER12=8\n"
"IS_SET_CM_Y16=2\n"
"IS_SET_CM_BAYER16=8\n"
"IS_CM_BGR12_UNPACKED=2\n"
"IS_CM_BGRA12_UNPACKED=2\n"
"IS_CM_JPEG=0\n"
"IS_CM_SENSOR_RAW10=8\n"
"IS_CM_MONO10=2\n"
"IS_CM_BGR10_UNPACKED=2\n"
"IS_CM_RGBA8_PACKED=2\n"
"IS_CM_RGB8_PACKED=2\n"
"IS_CM_RGBY8_PACKED=8\n"
"IS_CM_RGB10V2_PACKED=8\n"
"IS_CM_RGB12_UNPACKED=2\n"
"IS_CM_RGBA12_UNPACKED=2\n"
"IS_CM_RGB10_UNPACKED=2\n"
"IS_CM_RGB8_PLANAR=2\n"
"\n"
"\n"
"[Parameters]\n"
"Colormode=#COLOR_MODE#\n"
"Gamma=1.000000\n"
"Hardware Gamma=0\n"
"Blacklevel Mode=0\n"
"Blacklevel Offset=4\n"
"Hotpixel Mode=2\n"
"Hotpixel Threshold=0\n"
"Sensor Hotpixel=0\n"
"Adaptive hotpixel correction enable=0\n"
"Adaptive hotpixel correction mode=0\n"
"Adaptive hotpixel correction sensitivity=2\n"
"GlobalShutter=0\n"
"AllowRawWithLut=0\n"
"\n"
"\n"
"[Gain]\n"
"Master=0\n"
"Red=32\n"
"Green=0\n"
"Blue=52\n"
"GainBoost=0\n"
"\n"
"\n"
"[Processing]\n"
"EdgeEnhancementFactor=0\n"
"RopEffect=0\n"
"Whitebalance=0\n"
"Whitebalance Red=1.000000\n"
"Whitebalance Green=1.000000\n"
"Whitebalance Blue=1.000000\n"
"Color correction=0\n"
"Color_correction_factor=1.000000\n"
"Color_correction_satU=100\n"
"Color_correction_satV=100\n"
"Bayer Conversion=1\n"
"JpegCompression=0\n"
"NoiseMode=0\n"
"ImageEffect=0\n"
"LscModel=0\n"
"WideDynamicRange=0\n"
"\n"
"\n"
"[Auto features]\n"
"Auto Framerate control=0\n"
"Brightness exposure control=#ENABLE_AUTO_SHUTTER#\n"
"Brightness gain control=0\n"
"Auto Framerate Sensor control=0\n"
"Brightness exposure Sensor control=0\n"
"Brightness gain Sensor control=0\n"
"Brightness exposure Sensor control photometry=0\n"
"Brightness gain Sensor control photometry=0\n"
"Brightness control once=0\n"
"Brightness reference=#AUTO_REFERENCE#\n"
"Brightness speed=#AUTO_SPEED#\n"
"Brightness max gain=100\n"
"Brightness max exposure=66.637432\n"
"Brightness Aoi Left=0\n"
"Brightness Aoi Top=0\n"
"Brightness Aoi Width=3088\n"
"Brightness Aoi Height=2076\n"
"Brightness Hysteresis=2\n"
"AutoImageControlMode=2\n"
"AutoImageControlPeakWhiteChannel=0\n"
"AutoImageControlExposureMinimum=0.000000\n"
"Auto WB control=0\n"
"Auto WB type=2\n"
"Auto WB RGB color model=2\n"
"Auto WB RGB color temperature=5000\n"
"Auto WB offsetR=0\n"
"Auto WB offsetB=0\n"
"Auto WB gainMin=0\n"
"Auto WB gainMax=100\n"
"Auto WB speed=50\n"
"Auto WB Aoi Left=0\n"
"Auto WB Aoi Top=0\n"
"Auto WB Aoi Width=3088\n"
"Auto WB Aoi Height=2076\n"
"Auto WB Once=0\n"
"Auto WB Hysteresis=2\n"
"Brightness Skip Frames Trigger Mode=4\n"
"Brightness Skip Frames Freerun Mode=4\n"
"Auto WB Skip Frames Trigger Mode=4\n"
"Auto WB Skip Frames Freerun Mode=4\n"
"\n"
"\n"
"[Trigger and Flash]\n"
"Trigger mode=0\n"
"Trigger timeout=200\n"
"Trigger delay=0\n"
"Trigger debounce mode=0\n"
"Trigger debounce delay time=0\n"
"Trigger burst size=1\n"
"Trigger prescaler frame=1\n"
"Trigger prescaler line=1\n"
"Trigger input=1\n"
"Flash strobe=0\n"
"Flash delay=0\n"
"Flash duration=0\n"
"Flash auto freerun=0\n"
"PWM mode=0\n"
"PWM frequency=62500000\n"
"PWM dutycycle=62500000\n"
"GPIO state=3\n"
"GPIO direction=0\n"
"GPIO1 Config=1\n"
"GPIO2 Config=1\n"
"\n"
"\n"
"[Vertical AOI Merge Mode]\n"
"Mode=0\n"
"Position=0\n"
"Additional Position=0\n"
"Height=2\n"
"\n"
"\n"
"[Memory]\n"
"Camera memory mode=1\n"
"\n"
"\n"
;

}